/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import java.sql.Timestamp;

import br.com.control.CidadeControl;
import br.com.model.CidadeForm;
import br.com.util.Util;

/**
 *
 * @author Trusty
 */


/**
 * 
 * @version Thiago de Lima Gonçalves RA: 100838359
 *
 */
public class AlterarCidadeGUI extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5352239007146562964L;
	/**
     * Creates new form InserirCidadeGUI
     */
    public AlterarCidadeGUI() {
    	initComponents();
        
    }
    
    public AlterarCidadeGUI(Integer codigoCidade) {
        initComponents();
        
        CidadeForm cidadeForm = new CidadeForm();
        cidadeForm.setCidade_id(codigoCidade);
        CidadeControl.obtemCidade(cidadeForm);
        jtfcodigoCidade.setText(String.valueOf(cidadeForm.getCidade_id()));
        jtfcidade.setText(cidadeForm.getCidade());
        jtfpais_id.setText(String.valueOf(cidadeForm.getPais_id()));
        jtfModificacao.setText(new Timestamp(System.currentTimeMillis()).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfcidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfpais_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfModificacao = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfcodigoCidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Primeiro Nome:");

        jLabel2.setText("Último Nome: ");

        jLabel3.setText("Modificação: ");

        jtfModificacao.setColumns(20);
        jtfModificacao.setEditable(false);
        jtfModificacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(75, 23));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Código Ator:");

        jtfcodigoCidade.setEditable(false);
        jtfcodigoCidade.setPreferredSize(new java.awt.Dimension(70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfcidade)
                        .addComponent(jtfpais_id)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                            .addComponent(btnCancelar))
                        .addComponent(jtfModificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfcodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfcodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfpais_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfModificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	try {
	    	
    		//Integer atorId = Integer.parseInt(jtfcodigoCidade.getText());
	        String cidade = jtfcidade.getText();
	        Integer pais_id =Integer.parseInt(jtfpais_id.getText());
	        String ultimaAtualizacao = jtfModificacao.getText();
	                        
	        CidadeForm cidadeForm = new CidadeForm();
	      //  cidadeForm.setCidade_id(atorId);
	        cidadeForm.setCidade(cidade);
	        cidadeForm.setPais_id(pais_id);
			cidadeForm.setUltima_atualizacao(Util.formatarData(ultimaAtualizacao));

			CidadeControl.atualizarCidade(cidadeForm);

    	} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

        EditarRemoverCidadeGUI.atualizaTabela();
        this.dispose();
    }                                         

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	this.dispose();
    }                                           
    
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtfcodigoCidade;
    private javax.swing.JFormattedTextField jtfModificacao;
    private javax.swing.JTextField jtfcidade;
    private javax.swing.JTextField jtfpais_id;
    // End of variables declaration                   
}
